### ISSUE TITLE
感觉题目描述的好模糊啊

### ISSUE THREAD

**Issue by FerrariCalifornia** [wenxingyu/Quiz#1]
能具体些吗。。。

**Comment by wenxingyu** [comment]
输入：书的种类和数量
输出：价格
举个例子：买了1本新书（10元）、1本常规图书（10元）、1本滞销图书（10元）
得出的价格应该是：10 * 1.2 + 10 * 1 + 10 * 0.6 = 28元

**Comment by xuzhenzhen0320** [comment]
输入包含这本原本的价格吗？还是说这些书原本的价格都是一样的？
